# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InuMarket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InuMarket

pod 'SnapKit', '~> 4.0.0'
pod 'KYDrawerController'
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher'
pod 'ImageSlideshow', '~> 1.6'
pod 'IQKeyboardManagerSwift'
pod 'SwiftLint'
pod 'Toast-Swift', '~> 3.0.1'


end
