# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InuMarket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InuMarket

pod 'ImageSlideshow', '~> 1.6'
pod 'Kingfisher'
pod "BSImagePicker"
pod 'Alamofire', '~> 4.7'
pod 'CodableAlamofire'
pod "Device", '~> 3.1.2'
pod 'IQKeyboardManagerSwift'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'DropDown'
pod "ImageSlideshow/Kingfisher"
pod 'SideMenu'

end
