# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InuMarket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InuMarket

pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher'
pod 'ImageSlideshow', '~> 1.6'
pod 'IQKeyboardManagerSwift'
pod 'SwiftLint'
pod 'Toast-Swift', '~> 3.0.1'
pod 'SideMenu'
pod 'BetterSegmentedControl', '~> 0.9'
pod 'NohanaImagePicker'
pod 'ObjectMapper', '~> 3.1'
pod 'AlamofireObjectMapper', '~> 5.0'
pod 'DropDown'

end
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
